# Generated by Django 3.1.4 on 2024-11-20 16:26

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import vitrine_digital.helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=254)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagem_Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', stdimage.models.StdImageField(default='default_produto.jpg', force_min_size=False, upload_to=vitrine_digital.helper.retornaCaminhoImagemAleatorio, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=254, verbose_name='Descrição do produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço do produto')),
                ('qtd', models.IntegerField(default=0, verbose_name='Quantidade em estoque')),
                ('ativo', models.BooleanField()),
                ('destaque', models.BooleanField()),
                ('categoria_produto', models.ManyToManyField(to='produtos.Categoria_Produto')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empresas.empresa')),
                ('imagem_produto', models.ManyToManyField(to='produtos.Imagem_Produto')),
            ],
        ),
    ]
