# Generated by Django 3.1.4 on 2024-11-14 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=254)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=254, verbose_name='Descrição do produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço do produto')),
                ('qtd', models.IntegerField(default=0, verbose_name='Quantidade em estoque')),
                ('ativo', models.BooleanField()),
                ('destaque', models.BooleanField()),
                ('id_categoria_produto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produtos.categoriaproduto')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empresas.empresa')),
            ],
        ),
    ]
