# Generated by Django 3.1.4 on 2024-10-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='descricao',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.CharField(max_length=254),
        ),
    ]
