# Generated by Django 3.1.4 on 2024-11-14 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaProduto',
            new_name='Categoria_Produto',
        ),
    ]
