# Generated by Django 3.1.4 on 2024-10-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20241020_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='qtd',
            field=models.IntegerField(default=0, verbose_name='Quantidade em estoque'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.CharField(max_length=254, verbose_name='Descrição do produto'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço do produto'),
        ),
    ]
