# Generated by Django 3.1.4 on 2024-11-14 00:38

from django.db import migrations, models
import stdimage.models
import vitrine_digital.helper


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20241113_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem_Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', stdimage.models.StdImageField(default='default_produto.jpg', force_min_size=False, upload_to=vitrine_digital.helper.retornaCaminhoImagemAleatorio, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='imagem')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_produto',
            field=models.ManyToManyField(to='produtos.Imagem_Produto'),
        ),
    ]
