# Generated by Django 3.1.4 on 2024-12-06 16:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import vitrine_digital.helper


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20241202_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem_produto',
        ),
        migrations.AddField(
            model_name='imagem_produto',
            name='id_produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='produtos.produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagem_produto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagem_produto',
            name='imagem',
            field=models.ImageField(upload_to=vitrine_digital.helper.retornaCaminhoImagemAleatorio),
        ),
    ]
