# Generated by Django 3.1.4 on 2024-11-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20241113_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='id_categoria_produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria_produto',
            field=models.ManyToManyField(to='produtos.Categoria_Produto'),
        ),
    ]
