# Generated by Django 3.1.4 on 2024-12-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20241206_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem_produto',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
    ]
