# Generated by Django 3.1.4 on 2024-12-08 21:12

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import vitrine_digital.helper


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_auto_20241207_1401'),
        ('produtos', '0004_auto_20241206_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem_produto',
            name='imagem',
            field=stdimage.models.StdImageField(default='default_produto.jpg', force_min_size=False, upload_to=vitrine_digital.helper.retornaCaminhoImagemAleatorio, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem perfil'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
