# Generated by Django 3.1.4 on 2024-12-09 14:06

from django.db import migrations
import stdimage.models
import vitrine_digital.helper


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20241208_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem_produto',
            name='imagem',
            field=stdimage.models.StdImageField(default='default_produto.jpg', force_min_size=False, upload_to=vitrine_digital.helper.retornaCaminhoImagemAleatorio, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem produto'),
        ),
    ]
