# Generated by Django 3.1.4 on 2024-12-11 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_auto_20241209_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default='Nome teste', max_length=254, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria_produto',
            name='descricao',
            field=models.CharField(max_length=254, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='imagem_produto',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Produto em destaque'),
        ),
    ]
