# Generated by Django 3.1.4 on 2025-03-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_auto_20241211_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_oferta',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Preço com desconto do produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='qtd_visualizacoes',
            field=models.IntegerField(default=0, verbose_name='Quantidade de visualizações'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qtd',
            field=models.IntegerField(default=0, null=True, verbose_name='Quantidade em estoque'),
        ),
    ]
