# Generated by Django 3.1.4 on 2025-06-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_auto_20250330_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço com desconto do produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade em estoque'),
        ),
    ]
