# Generated by Django 3.1.4 on 2024-10-20 14:42

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cpf',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255, unique=True)),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(max_length=255, unique=True)),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255, verbose_name='first name')),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255, verbose_name='last name')),
        ),
    ]
