# Generated by Django 3.1.4 on 2024-11-14 00:38

from django.db import migrations
import stdimage.models
import vitrine_digital.helper


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=stdimage.models.StdImageField(default='default_profile.jpg', force_min_size=False, upload_to=vitrine_digital.helper.retornaCaminhoImagemAleatorio, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='imagem'),
        ),
    ]
