# Generated by Django 3.1.4 on 2024-10-20 14:49

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20241020_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cpf',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
