# Generated by Django 3.1.4 on 2024-12-06 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20241201_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Assinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=254, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Lojista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pedido', models.CharField(max_length=254, verbose_name='Estado do pedido')),
                ('ultimo_pagamento', models.DateTimeField(verbose_name='Data do último pagamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('id_tipo_assinatura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuarios.tipo_assinatura')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
