# Generated by Django 3.1.4 on 2024-10-20 15:04

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20241020_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255, unique=True)),
        ),
    ]
