# Generated by Django 3.1.4 on 2024-12-08 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_pedido_lojista_tipo_assinatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_lojista',
            name='id_tipo_assinatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.tipo_assinatura'),
        ),
        migrations.AlterField(
            model_name='pedido_lojista',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
