# Generated by Django 3.1.4 on 2024-12-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20241208_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_lojista',
            name='ultimo_pagamento',
            field=models.DateTimeField(blank=True, verbose_name='Data do último pagamento'),
        ),
    ]
