# Generated by Django 3.1.4 on 2024-12-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20241209_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_lojista',
            name='ultimo_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do último pagamento'),
        ),
    ]
