# Generated by Django 3.1.4 on 2024-12-10 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20241209_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_lojista',
            name='id_tipo_assinatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.tipo_assinatura'),
        ),
    ]
