# Generated by Django 3.1.4 on 2024-12-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_auto_20241208_1949'),
        ('produtos', '0006_auto_20241209_1106'),
        ('usuarios', '0008_auto_20241210_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='favorito_empresa',
            field=models.ManyToManyField(related_name='favoritos_empresas', to='empresas.Empresa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='favorito_produto',
            field=models.ManyToManyField(related_name='favoritos_produtos', to='produtos.Produto'),
        ),
    ]
