# Generated by Django 3.1.4 on 2024-12-11 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_empresa_descricao'),
        ('usuarios', '0009_auto_20241210_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresas.cidade', verbose_name='Cidade para pesquisa'),
        ),
    ]
