# Generated by Django 3.1.4 on 2024-10-20 17:35

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20241020_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=254, unique=True, verbose_name='email')),
        ),
    ]
