# Generated by Django 3.1.4 on 2024-10-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20241020_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cpf',
            field=models.CharField(max_length=254, unique=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='first_name',
            field=models.CharField(max_length=254, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='last_name',
            field=models.CharField(max_length=254, verbose_name='last name'),
        ),
    ]
