# Generated by Django 3.1.4 on 2025-04-01 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_auto_20250330_0020'),
        ('empresas', '0013_auto_20250330_0020'),
        ('usuarios', '0011_auto_20250330_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='visualizacao_empresa',
            field=models.ManyToManyField(related_name='visualizacoes_empresas', to='empresas.Empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='visualizacao_produto',
            field=models.ManyToManyField(related_name='visualizacoes_produtos', to='produtos.Produto'),
        ),
        migrations.CreateModel(
            name='Visualizacao_Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.produto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visualizacao_produto_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visualizacao_Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresas.empresa')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visualizacao_empresa_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
