# Generated by Django 3.1.4 on 2025-04-01 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_auto_20250330_0020'),
        ('empresas', '0013_auto_20250330_0020'),
        ('usuarios', '0012_auto_20250401_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizacao_empresa',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='visualizacao_empresa',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacao_empresa_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visualizacao_produto',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='visualizacao_produto',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacao_produto_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
