# Generated by Django 3.1.4 on 2025-04-01 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20250401_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='visualizacao_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='visualizacao_produto',
        ),
    ]
