# Generated by Django 3.1.4 on 2025-06-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20250401_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nascimento',
            field=models.DateField(
                verbose_name='Data de nascimento'
            ),
            preserve_default=False,
        ),
    ]
