# Generated by Django 3.1.4 on 2025-06-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_usuario_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nascimento',
            field=models.CharField(max_length=254, verbose_name='Data de nascimento'),
        ),
    ]
