# Generated by Django 3.1.4 on 2025-06-08 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_auto_20250602_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_lojista',
            name='id_tipo_assinatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.tipo_assinatura', verbose_name='Tipo de assinatura'),
        ),
        migrations.AlterField(
            model_name='pedido_lojista',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
