# Generated by Django 3.1.4 on 2025-06-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_auto_20250608_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(max_length=254, verbose_name='Sobrenome'),
        ),
    ]
