# Generated by Django 3.1.4 on 2024-11-14 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=254)),
                ('cor', models.CharField(max_length=254)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=254)),
                ('numero', models.CharField(max_length=254)),
                ('complemento', models.CharField(max_length=254)),
                ('bairro', models.CharField(max_length=254)),
                ('ativo', models.BooleanField()),
                ('id_cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('nome_fantasia', models.CharField(max_length=254)),
                ('razao_social', models.CharField(max_length=254)),
                ('ativo', models.BooleanField()),
                ('situacao', models.CharField(max_length=30)),
                ('enderecos', models.ManyToManyField(to='empresas.Endereco')),
                ('id_categoria_empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empresas.categoriaempresa')),
            ],
        ),
    ]
