# Generated by Django 5.1.2 on 2024-11-28 22:02

import stdimage.models
import vitrine_digital.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=254)),
                ('cor', models.CharField(max_length=254)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=254)),
                ('numero', models.CharField(max_length=254)),
                ('complemento', models.CharField(max_length=254)),
                ('bairro', models.CharField(max_length=254)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=254)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('nome_fantasia', models.CharField(max_length=254)),
                ('razao_social', models.CharField(max_length=254)),
                ('ativo', models.BooleanField()),
                ('situacao', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=30)),
                ('imagem_capa', stdimage.models.StdImageField(default='default_capa_empresa.jpg', force_min_size=False, upload_to=vitrine_digital.helper.retornaCaminhoImagemAleatorio, variations={'mid': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='imagem')),
                ('imagem_perfil', stdimage.models.StdImageField(default='default_perfil_empresa.jpg', force_min_size=False, upload_to=vitrine_digital.helper.retornaCaminhoImagemAleatorio, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='imagem')),
                ('categoria_produto', models.ManyToManyField(to='empresas.categoria_empresa')),
            ],
        ),
    ]
