# Generated by Django 3.1.4 on 2024-11-14 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20241113_2123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaEmpresa',
            new_name='Categoria_Empresa',
        ),
    ]
