# Generated by Django 3.1.4 on 2024-10-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20241019_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidades',
            name='descricao',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nome_fantasia',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='razao_social',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='bairro',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='complemento',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='logradouro',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='numero',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='estados',
            name='descricao',
            field=models.CharField(max_length=254),
        ),
    ]
