# Generated by Django 3.1.4 on 2024-12-02 19:50

from django.db import migrations, models
import stdimage.models
import vitrine_digital.helper


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20241201_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_empresa',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagem_capa',
            field=stdimage.models.StdImageField(default='default_capa_empresa.jpg', force_min_size=False, upload_to=vitrine_digital.helper.retornaCaminhoImagemAleatorio, variations={'mid': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='imagem_capa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagem_perfil',
            field=stdimage.models.StdImageField(default='default_perfil_empresa.jpg', force_min_size=False, upload_to=vitrine_digital.helper.retornaCaminhoImagemAleatorio, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='imagem_perfil'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
