# Generated by Django 3.1.4 on 2024-11-14 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20241113_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='enderecos',
            new_name='endereco',
        ),
    ]
