# Generated by Django 3.1.4 on 2024-11-14 00:38

from django.db import migrations
import stdimage.models
import vitrine_digital.helper


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_auto_20241113_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='endereco',
            new_name='empresa_endereco',
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagem_capa',
            field=stdimage.models.StdImageField(default='default_capa_empresa.jpg', force_min_size=False, upload_to=vitrine_digital.helper.retornaCaminhoImagemAleatorio, variations={'mid': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='imagem'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagem_perfil',
            field=stdimage.models.StdImageField(default='default_perfil_empresa.jpg', force_min_size=False, upload_to=vitrine_digital.helper.retornaCaminhoImagemAleatorio, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='imagem'),
        ),
    ]
