# Generated by Django 3.1.4 on 2024-12-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_auto_20241202_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='categoria_produto',
            new_name='empresa_categoria',
        ),
    ]
