# Generated by Django 3.1.4 on 2024-12-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_auto_20241204_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='situacao',
        ),
    ]
