# Generated by Django 3.1.4 on 2024-11-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_auto_20241113_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='id_categoria_empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='categoria_produto',
            field=models.ManyToManyField(to='empresas.Categoria_Empresa'),
        ),
    ]
