# Generated by Django 3.1.4 on 2024-12-04 20:22

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import vitrine_digital.helper


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_remove_empresa_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_empresa',
            name='cor',
            field=models.CharField(max_length=254, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='categoria_empresa',
            name='descricao',
            field=models.CharField(max_length=254, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='descricao',
            field=models.CharField(max_length=254, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagem_capa',
            field=stdimage.models.StdImageField(default='default_capa_empresa.jpg', force_min_size=False, upload_to=vitrine_digital.helper.retornaCaminhoImagemAleatorio, variations={'mid': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem capa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagem_perfil',
            field=stdimage.models.StdImageField(default='default_perfil_empresa.jpg', force_min_size=False, upload_to=vitrine_digital.helper.retornaCaminhoImagemAleatorio, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem perfil'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(max_length=254, verbose_name='Nome fantasia'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(max_length=254, verbose_name='Razão social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(max_length=30, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=254, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=254, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id_cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(max_length=254, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(max_length=254, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='descricao',
            field=models.CharField(max_length=254, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='uf',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
    ]
