# Generated by Django 3.1.4 on 2024-12-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_auto_20241204_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default=88677, max_length=254, verbose_name='CEP'),
            preserve_default=False,
        ),
    ]
