# Generated by Django 3.1.4 on 2024-12-07 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_endereco_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='empresa_endereco',
        ),
        migrations.AddField(
            model_name='endereco',
            name='id_empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
