# Generated by Django 3.1.4 on 2024-12-08 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0009_auto_20241207_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id_cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresas.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa'),
        ),
    ]
