# Generated by Django 3.1.4 on 2024-12-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_auto_20241208_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='descricao',
            field=models.CharField(default='descrição teste', max_length=254, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
