# Generated by Django 3.1.4 on 2025-03-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_empresa_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='link_facebook',
            field=models.CharField(max_length=254, null=True, verbose_name='Link para Facebook'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='link_instagram',
            field=models.CharField(max_length=254, null=True, verbose_name='Link para Instagram'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='link_whatsapp',
            field=models.CharField(max_length=254, null=True, verbose_name='Link para Whatsapp'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='qtd_visualizacoes',
            field=models.IntegerField(default=0, verbose_name='Quantidade de visualizações'),
        ),
    ]
