# Generated by Django 3.1.4 on 2025-06-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_auto_20250330_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='link_facebook',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Link para Facebook'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='link_instagram',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Link para Instagram'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='link_whatsapp',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Link para Whatsapp'),
        ),
    ]
